filebeat.inputs:

# user_login = access = auth stats (triggered by ?)
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/user_login.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.user_login.20190313"



# b2safe_op = b2safe_operation = b2safe_b2safe (triggered by ?)
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/b2safe_op.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.b2safe_op.20190313"



# user_op = operation (triggered by rules)
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/user_op.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.user_op.20190313"


# quota_stats = acc = accounting_stats = irods_accounting (triggered by cron job)
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/quota.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.quota_stats.20190313"

- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/quota-error.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.user_op.error.20190313"

# system_stats = sys (triggered by cron job)
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/system_stats.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.system_stats.20190313"

- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/irods_accounting_logs/system_stats-error.log"
  fields_under_root: true
  fields:
    is_seadata: true
    is_apel_accounting: true
    is_from_eudat_seadata_filebeat: true
    filter_code: "de.dkrz.seadata.filter_code.apel.20190313"
    log_type: "de.dkrz.seadata.filter_code.apel.system_stats.error.20190313"

###
### Output to Logstash
###
output.logstash:
  hosts: ["my-logstash.de:5044"]


###
### Optional:
### Logging of Filebeat itself
###
#https://www.elastic.co/guide/en/beats/filebeat/current/configuration-logging.html
logging.level: info
logging.json: true
logging.to_files: true
logging.metrics.enabled: false
logging.to_syslog: false
logging.to_eventlog: false
logging.files:
  path: /usr/share/filebeat/logs/
  name: filebeatlog
  keepfiles: 10

